#!/bin/sh

# Copyright 2026 Ethan Wang <ethanshurui.wang@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

: "${FAKE_CMAKE_LOG:?}"
: "${FAKE_POLICY_LOG:?}"
: "${FAKE_SOURCE_DIR:?}"

printf '%s\n' "$*" >> "$FAKE_CMAKE_LOG"

operation=configure
cmake_source=
cmake_build=
install_prefix=
mlx_root=
allow_downloads=
script_mode=no

while [ "$#" -gt 0 ]; do
    case "$1" in
        --build|--install)
            operation=${1#--}
            ;;
        -S)
            shift
            cmake_source=$1
            ;;
        -B)
            shift
            cmake_build=$1
            ;;
        --prefix)
            shift
            install_prefix=$1
            ;;
        -P)
            script_mode=yes
            ;;
        -DMLX_ROOT:PATH=*)
            mlx_root=${1#-DMLX_ROOT:PATH=}
            ;;
        -DMLXPDLP_ALLOW_DOWNLOADS:BOOL=*)
            allow_downloads=${1#-DMLXPDLP_ALLOW_DOWNLOADS:BOOL=}
            ;;
    esac
    shift
done

if [ "$script_mode" = yes ]; then
    if [ "${FAKE_MLX_AVAILABLE:-no}" = yes ]; then
        exit 0
    fi
    if [ -n "$mlx_root" ] && [ -f "$mlx_root/.fake-installed" ]; then
        exit 0
    fi
    exit 1
fi

case "$operation" in
    build)
        exit 0
        ;;
    install)
        mkdir -p "$install_prefix"
        : > "$install_prefix/.fake-installed"
        exit 0
        ;;
esac

if [ "$cmake_source" = "$FAKE_SOURCE_DIR" ]; then
    mkdir -p "$cmake_build"
    printf '%s\n' "$allow_downloads" >> "$FAKE_POLICY_LOG"
    if [ "${FAKE_PSLP_MISSING:-no}" = yes ] &&
       [ "$allow_downloads" = OFF ]; then
        printf '%s\n' "PSLP 0.0.11" > "$cmake_build/.mlxpdlp-missing-pslp"
        exit 1
    fi
fi

exit 0
